import fs from 'fs';
import path from 'path';

/**
 * Names of different functions that can be used to create a component in ReasonReact
 * Used to parse the name from page components to create the URL path
 */
export const COMPONENT_FUNCS = [
    'statelessComponent',
    'statelessComponentWithRetainedProps',
    'reducerComponent',
    'reducerComponentWithRetainedProps'
];

// TODO can we parse the AST generated by refmt to more reliably get the component name?
const isComponentDefinitionLine = line => line.indexOf('let component') !== -1;

/**
 * Find the line that contains the component definition
 */
export const getComponentDefinitionLine = fileSource =>
    fileSource
        .split('\n')
        .filter(Boolean)
        .filter(isComponentDefinitionLine)[0];

export const getNameFromReasonComponent = componentDef =>
    COMPONENT_FUNCS.map(func => new RegExp(`${func}\\("(.*?)"\\)`))
        .map(regex => regex.exec(componentDef))
        .filter(Boolean)
        .map(regexMatch => regexMatch[1])[0];

/**
 * Given the source for a page component's file, parse the contents of the file
 * in order to determine the URL path for the page. This will use the name
 * of the ReasonReact component defined in the file.
 *
 * e.g. if the source contains
 * ```ocaml
 * let component = ReasonReact.statelessComponent("MyComponent");
 * ```
 * this will return `'MyComponent'`
 */
export const getPathForComponent = source => {
    const line = getComponentDefinitionLine(source);
    if (!line) {
        return;
    }

    const name = getNameFromReasonComponent(line);
    return name === 'index' ? '/' : `/${name}/`;
};
